# Generated by Django 4.0.4 on 2022-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo',
        ),
        migrations.AddField(
            model_name='property',
            name='photo_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
