# Generated by Django 4.0.4 on 2022-12-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Dallas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(default='House', max_length=255),
            preserve_default=False,
        ),
    ]
