# Generated by Django 4.0.4 on 2022-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_baths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
